class BlazerRunner{

	public static void main(String[] blazer){
		
		Blazer firstBlazer = new Blazer();
		firstBlazer.blazerId = 1;
		firstBlazer.colour = "black";
		firstBlazer.noOfPockets = 2;
		firstBlazer.noOfButtons = 3;
		firstBlazer.typeOfMaterial = "cotton";
		firstBlazer.type = "casuals";
		System.out.println("the blazer id is " + firstBlazer.blazerId );
		System.out.println("the colour is "+firstBlazer.colour);
		System.out.println("the number of pockets are "+firstBlazer.noOfPockets);
		System.out.println("the number of buttons are "+firstBlazer.noOfButtons);
		System.out.println("the material is "+firstBlazer.typeOfMaterial);
		System.out.println("the type of blazer is "+firstBlazer.type );
		System.out.println();
		
		Blazer secondBlazer = new Blazer();
        secondBlazer.blazerId = 2;
        secondBlazer.colour = "blue";
        secondBlazer.noOfPockets = 3;
        secondBlazer.noOfButtons = 2;
        secondBlazer.typeOfMaterial = "wool";
        secondBlazer.type = "formals";
        System.out.println("the blazer id is " + secondBlazer.blazerId);
        System.out.println("the colour is " + secondBlazer.colour);
        System.out.println("the number of pockets are " + secondBlazer.noOfPockets);
        System.out.println("the number of buttons are " + secondBlazer.noOfButtons);
        System.out.println("the material is " + secondBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + secondBlazer.type);
        System.out.println();

        Blazer thirdBlazer = new Blazer();
        thirdBlazer.blazerId = 3;
        thirdBlazer.colour = "grey";
        thirdBlazer.noOfPockets = 2;
        thirdBlazer.noOfButtons = 4;
        thirdBlazer.typeOfMaterial = "linen";
        thirdBlazer.type = "party wear";
        System.out.println("the blazer id is " + thirdBlazer.blazerId);
        System.out.println("the colour is " + thirdBlazer.colour);
        System.out.println("the number of pockets are " + thirdBlazer.noOfPockets);
        System.out.println("the number of buttons are " + thirdBlazer.noOfButtons);
        System.out.println("the material is " + thirdBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + thirdBlazer.type);
        System.out.println();

        Blazer fourthBlazer = new Blazer();
        fourthBlazer.blazerId = 4;
        fourthBlazer.colour = "navy blue";
        fourthBlazer.noOfPockets = 1;
        fourthBlazer.noOfButtons = 2;
        fourthBlazer.typeOfMaterial = "cotton";
        fourthBlazer.type = "formals";
        System.out.println("the blazer id is " + fourthBlazer.blazerId);
        System.out.println("the colour is " + fourthBlazer.colour);
        System.out.println("the number of pockets are " + fourthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + fourthBlazer.noOfButtons);
        System.out.println("the material is " + fourthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + fourthBlazer.type);
        System.out.println();

        Blazer fifthBlazer = new Blazer();
        fifthBlazer.blazerId = 5;
        fifthBlazer.colour = "brown";
        fifthBlazer.noOfPockets = 2;
        fifthBlazer.noOfButtons = 3;
        fifthBlazer.typeOfMaterial = "denim";
        fifthBlazer.type = "casuals";
        System.out.println("the blazer id is " + fifthBlazer.blazerId);
        System.out.println("the colour is " + fifthBlazer.colour);
        System.out.println("the number of pockets are " + fifthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + fifthBlazer.noOfButtons);
        System.out.println("the material is " + fifthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + fifthBlazer.type);
        System.out.println();

        Blazer sixthBlazer = new Blazer();
        sixthBlazer.blazerId = 6;
        sixthBlazer.colour = "white";
        sixthBlazer.noOfPockets = 2;
        sixthBlazer.noOfButtons = 2;
        sixthBlazer.typeOfMaterial = "cotton";
        sixthBlazer.type = "formals";
        System.out.println("the blazer id is " + sixthBlazer.blazerId);
        System.out.println("the colour is " + sixthBlazer.colour);
        System.out.println("the number of pockets are " + sixthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + sixthBlazer.noOfButtons);
        System.out.println("the material is " + sixthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + sixthBlazer.type);
        System.out.println();

        Blazer seventhBlazer = new Blazer();
        seventhBlazer.blazerId = 7;
        seventhBlazer.colour = "maroon";
        seventhBlazer.noOfPockets = 3;
        seventhBlazer.noOfButtons = 2;
        seventhBlazer.typeOfMaterial = "wool";
        seventhBlazer.type = "partywear";
        System.out.println("the blazer id is " + seventhBlazer.blazerId);
        System.out.println("the colour is " + seventhBlazer.colour);
        System.out.println("the number of pockets are " + seventhBlazer.noOfPockets);
        System.out.println("the number of buttons are " + seventhBlazer.noOfButtons);
        System.out.println("the material is " + seventhBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + seventhBlazer.type);
        System.out.println();

        Blazer eighthBlazer = new Blazer();
        eighthBlazer.blazerId = 8;
        eighthBlazer.colour = "olive";
        eighthBlazer.noOfPockets = 2;
        eighthBlazer.noOfButtons = 3;
        eighthBlazer.typeOfMaterial = "denim";
        eighthBlazer.type = "casuals";
        System.out.println("the blazer id is " + eighthBlazer.blazerId);
        System.out.println("the colour is " + eighthBlazer.colour);
        System.out.println("the number of pockets are " + eighthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + eighthBlazer.noOfButtons);
        System.out.println("the material is " + eighthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + eighthBlazer.type);
        System.out.println();

        Blazer ninthBlazer = new Blazer();
        ninthBlazer.blazerId = 9;
        ninthBlazer.colour = "red";
        ninthBlazer.noOfPockets = 1;
        ninthBlazer.noOfButtons = 1;
        ninthBlazer.typeOfMaterial = "linen";
        ninthBlazer.type = "summer";
        System.out.println("the blazer id is " + ninthBlazer.blazerId);
        System.out.println("the colour is " + ninthBlazer.colour);
        System.out.println("the number of pockets are " + ninthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + ninthBlazer.noOfButtons);
        System.out.println("the material is " + ninthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + ninthBlazer.type);
        System.out.println();

        Blazer tenthBlazer = new Blazer();
        tenthBlazer.blazerId = 10;
        tenthBlazer.colour = "blue";
        tenthBlazer.noOfPockets = 2;
        tenthBlazer.noOfButtons = 2;
        tenthBlazer.typeOfMaterial = "silk ";
        tenthBlazer.type = "wedding";
        System.out.println("the blazer id is " + tenthBlazer.blazerId);
        System.out.println("the colour is " + tenthBlazer.colour);
        System.out.println("the number of pockets are " + tenthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + tenthBlazer.noOfButtons);
        System.out.println("the material is " + tenthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + tenthBlazer.type);
        System.out.println();
		
		
		Blazer eleventhBlazer = new Blazer();
        eleventhBlazer.blazerId = 11;
        eleventhBlazer.colour = "green";
        eleventhBlazer.noOfPockets = 2;
        eleventhBlazer.noOfButtons = 3;
        eleventhBlazer.typeOfMaterial = "denim";
        eleventhBlazer.type = "casuals";
        System.out.println("the blazer id is " + eleventhBlazer.blazerId);
        System.out.println("the colour is " + eleventhBlazer.colour);
        System.out.println("the number of pockets are " + eleventhBlazer.noOfPockets);
        System.out.println("the number of buttons are " + eleventhBlazer.noOfButtons);
        System.out.println("the material is " + eleventhBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + eleventhBlazer.type);
        System.out.println();

        Blazer twelthBlazer = new Blazer();
        twelthBlazer.blazerId = 12;
        twelthBlazer.colour = "red";
        twelthBlazer.noOfPockets = 3;
        twelthBlazer.noOfButtons = 1;
        twelthBlazer.typeOfMaterial = "denim";
        twelthBlazer.type = "partywear";
        System.out.println("the blazer id is " + twelthBlazer.blazerId);
        System.out.println("the colour is " + twelthBlazer.colour);
        System.out.println("the number of pockets are " + twelthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + twelthBlazer.noOfButtons);
        System.out.println("the material is " + twelthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + twelthBlazer.type);
        System.out.println();

        Blazer thirteenthBlazer = new Blazer();
        thirteenthBlazer.blazerId = 13;
        thirteenthBlazer.colour = "blue";
        thirteenthBlazer.noOfPockets = 1;
        thirteenthBlazer.noOfButtons = 3;
        thirteenthBlazer.typeOfMaterial = "cotton";
        thirteenthBlazer.type = "formals";
        System.out.println("the blazer id is " + thirteenthBlazer.blazerId);
        System.out.println("the colour is " + thirteenthBlazer.colour);
        System.out.println("the number of pockets are " + thirteenthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + thirteenthBlazer.noOfButtons);
        System.out.println("the material is " + thirteenthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + thirteenthBlazer.type);
        System.out.println();

        Blazer fourteenthBlazer = new Blazer();
        fourteenthBlazer.blazerId = 14;
        fourteenthBlazer.colour = "sky blue";
        fourteenthBlazer.noOfPockets = 2;
        fourteenthBlazer.noOfButtons = 2;
        fourteenthBlazer.typeOfMaterial = "linen";
        fourteenthBlazer.type = "partywear";
        System.out.println("the blazer id is " + fourteenthBlazer.blazerId);
        System.out.println("the colour is " + fourteenthBlazer.colour);
        System.out.println("the number of pockets are " + fourteenthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + fourteenthBlazer.noOfButtons);
        System.out.println("the material is " + fourteenthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + fourteenthBlazer.type);
        System.out.println();

        Blazer fifteenthBlazer = new Blazer();
        fifteenthBlazer.blazerId = 15;
        fifteenthBlazer.colour = "cream";
        fifteenthBlazer.noOfPockets = 3;
        fifteenthBlazer.noOfButtons = 2;
        fifteenthBlazer.typeOfMaterial = "khadi";
        fifteenthBlazer.type = "traditional";
        System.out.println("the blazer id is " + fifteenthBlazer.blazerId);
        System.out.println("the colour is " + fifteenthBlazer.colour);
        System.out.println("the number of pockets are " + fifteenthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + fifteenthBlazer.noOfButtons);
        System.out.println("the material is " + fifteenthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + fifteenthBlazer.type);
        System.out.println();

        Blazer sixteenthBlazer = new Blazer();
        sixteenthBlazer.blazerId = 16;
        sixteenthBlazer.colour = "dark green";
        sixteenthBlazer.noOfPockets = 2;
        sixteenthBlazer.noOfButtons = 3;
        sixteenthBlazer.typeOfMaterial = "cotton";
        sixteenthBlazer.type = "formals";
        System.out.println("the blazer id is " + sixteenthBlazer.blazerId);
        System.out.println("the colour is " + sixteenthBlazer.colour);
        System.out.println("the number of pockets are " + sixteenthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + sixteenthBlazer.noOfButtons);
        System.out.println("the material is " + sixteenthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + sixteenthBlazer.type);
        System.out.println();

        Blazer seventeenthBlazer = new Blazer();
        seventeenthBlazer.blazerId = 17;
        seventeenthBlazer.colour = "light grey";
        seventeenthBlazer.noOfPockets = 2;
        seventeenthBlazer.noOfButtons = 2;
        seventeenthBlazer.typeOfMaterial = "wool";
        seventeenthBlazer.type = "business";
        System.out.println("the blazer id is " + seventeenthBlazer.blazerId);
        System.out.println("the colour is " + seventeenthBlazer.colour);
        System.out.println("the number of pockets are " + seventeenthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + seventeenthBlazer.noOfButtons);
        System.out.println("the material is " + seventeenthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + seventeenthBlazer.type);
        System.out.println();

        Blazer eighteenthBlazer = new Blazer();
        eighteenthBlazer.blazerId = 18;
        eighteenthBlazer.colour = "pink";
        eighteenthBlazer.noOfPockets = 1;
        eighteenthBlazer.noOfButtons = 1;
        eighteenthBlazer.typeOfMaterial = "cotton ";
        eighteenthBlazer.type = "casuals";
        System.out.println("the blazer id is " + eighteenthBlazer.blazerId);
        System.out.println("the colour is " + eighteenthBlazer.colour);
        System.out.println("the number of pockets are " + eighteenthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + eighteenthBlazer.noOfButtons);
        System.out.println("the material is " + eighteenthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + eighteenthBlazer.type);
        System.out.println();

        Blazer nineteenthBlazer = new Blazer();
        nineteenthBlazer.blazerId = 19;
        nineteenthBlazer.colour = "black ";
        nineteenthBlazer.noOfPockets = 2;
        nineteenthBlazer.noOfButtons = 2;
        nineteenthBlazer.typeOfMaterial = "cotton";
        nineteenthBlazer.type = "college";
        System.out.println("the blazer id is " + nineteenthBlazer.blazerId);
        System.out.println("the colour is " + nineteenthBlazer.colour);
        System.out.println("the number of pockets are " + nineteenthBlazer.noOfPockets);
        System.out.println("the number of buttons are " + nineteenthBlazer.noOfButtons);
        System.out.println("the material is " + nineteenthBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + nineteenthBlazer.type);
        System.out.println();

        Blazer twentiethBlazer = new Blazer();
        twentiethBlazer.blazerId = 20;
        twentiethBlazer.colour = "gold";
        twentiethBlazer.noOfPockets = 3;
        twentiethBlazer.noOfButtons = 4;
        twentiethBlazer.typeOfMaterial = "silk";
        twentiethBlazer.type = "marraige";
        System.out.println("the blazer id is " + twentiethBlazer.blazerId);
        System.out.println("the colour is " + twentiethBlazer.colour);
        System.out.println("the number of pockets are " + twentiethBlazer.noOfPockets);
        System.out.println("the number of buttons are " + twentiethBlazer.noOfButtons);
        System.out.println("the material is " + twentiethBlazer.typeOfMaterial);
        System.out.println("the type of blazer is " + twentiethBlazer.type);
        System.out.println();
	
	}
}